config/routes.rb
Rails.application.routes.draw do
devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :hebs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heb.rb
class Heb < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  SECURITY_FEATURES = [
    "code à l'entrée",
    "caméra de surveillance 24h/24",
    "gardien 24h/24",
    "gardien à horaires définis",
    "autres"
  ]

  SERVICES = [
    "suivi psychologique",
    "accompagnement juridique",
    "garde d'enfants",
    "centre d'écoute",
    "autres"
  ]

  validates :security_features, presence: true, inclusion: { in: SECURITY_FEATURES }, on: :create
  validates :services, presence: true, inclusion: { in: SERVICES }, on: :create

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :email, :password, :password_confirmation, :remember_me, :name, :familyname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if:  :devise_controller?


protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :familyname])

  end
end

app/controllers/hebs_controller.rb
class HebsController < ApplicationController
skip_before_action :authenticate_user!, only: [ :index, :new, :create, :show ]

  def index
      if params[:query].present?
      hebs = Heb.geocoded.order(created_at: :asc)
      sql_query = "hebs.name ILIKE :query  OR hebs.address ILIKE :query"
        @hebs = hebs.where(sql_query, query: "%#{params[:query]}%")
      else
        @hebs = Heb.geocoded
      end

      @markers = @hebs.map do |heb|
      {
        lat: heb.latitude,
        lng: heb.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { heb: heb }),
        image_url: helpers.asset_url('picto-map.png')
      }
    end

    end

    def show
      @heb = Heb.find(params[:id])
    end

    def new
      @heb = Heb.new
    end

    def create
      @heb = Heb.new(heb_params)
      if @heb.save
        @hebs = Heb.geocoded
        render :index
      else
        render :new
      end
    end

  private

  def heb_params
      params.require(:heb).permit(:name, :address, :description)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hebs/_form.html.erb
<%= simple_form_for(@heb) do |h| %>

  <%= h.input :name, label: "Nom", placeholder: "Nom de l'hébergement" %>

  <%= h.input :address, label: "Adresse", placeholder: '13 rue Morand, Paris'  %>

  <%= h.input :description, label: 'Description' %>
  <%= h.submit "Valider", class: "btn btn-foyer"  %>
<% end %>

app/views/hebs/_info_window.html.erb
<h2><%= heb.name %></h2>

<p><%= heb.address %></p>
<button class="btn">
  <%= link_to "Selectionner", heb_path(heb) %>
</button>

app/views/hebs/index.html.erb
<div class="d-flex flex-row">

    <div class="list-heb mb-5">

        <h1 class="mt-5 mb-5">Trouver un hébergement</h1>

            <div class="d-flex flex-row">
                <%= form_tag hebs_path, method: :get, class: "searchbar form-inline search-form-control" do %>
                  <%= text_field_tag :query,
                    params[:query],
                    class: "td form-control",
                    placeholder: "Chercher un hébergement par nom, catégorie, adresse..."%>
                <% end %>

          </div>

          <% @hebs.each do |heb| %>

                <div class="cards d-flex flex-row justify-content-between">

                  <div class="d-flex flex-column">
                          <div class="d-flex flex-row">
                            <img class="building" src="<%= image_path('building.svg') %>"/>
                            <h3><%= heb.name.capitalize %></h3>
                          </div>
                    <p>📍<%= heb.address %></p>
                  </div>

                    <%= link_to "2 places", heb_path(heb), class: "btn btn-foyer" %>

                </div>

          <% end %>
    </div>


<!-- <img class="carte" src="<%#= image_path('building.svg') %>"/> -->
<div id="map" class="carte"
     style="width: 100%;
     height: 700px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

</div>

app/views/hebs/new.html.erb
<%= render 'shared/mini-banner' %>

<div class="container creerheb">

<h1 class="mb-4">Proposer un hébergement</h1>

<%= render 'form' %>

</div>

app/views/hebs/show.html.erb
<div class="container-show">

  <div class="d-flex flex-row justify-content-between">
    <div class="d-flex flex-column">
      <h1><%= @heb.name %></h1>
      <p><%= @heb.address %></p>
    </div>
     <div class="custom-control custom-switch">
       <input type="checkbox" class="custom-control-input" id="customSwitch1" onChange= "" checked>
       <label class="custom-control-label" for="customSwitch1">Dispo</label>
     </div>
  </div>

<img class="foyer-img" src="<%= image_path('building.svg') %>"/>

  <div class="mb-5"></div>

  <strong>Description</strong>

    <div class="mb-3"></div>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, debitis, maiores. Sed eos rem reiciendis, consectetur atque doloribus exercitationem vitae adipisci velit fuga placeat aliquam odit! Culpa illum, minima perspiciatis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum illum cupiditate facilis sequi at accusamus, atque possimus voluptatum, esse consequatur autem voluptates error officia optio, laudantium veritatis! Dolores, eligendi quod.</p>


    <div class="mb-3"></div>

  <strong>Option de sécurité</strong>

    <div class="mb-3"></div>

  <ul>
    <li>Lorem</li>
    <li>Lorem</li>
    <li>Lorem</li>
    <li>Lorem</li>
  </ul>

      <div class="mb-3"></div>


<div class="d-flex flex-column">
  <strong>Contacter l'espace</strong>
      <div class="mb-3"></div>


  <%= link_to "Afficher numéro", "", class: "btn btn-foyer" %>
</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ProtegeToit2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>




    <%= favicon_link_tag 'PROTEGE-TOIT.png'%>
    <%= stylesheet_link_tag 'application', media: 'all' %>

  </head>

  <body>

    <%= render 'shared/navbar' %>

    <%= yield %>
    <%= render 'shared/footer' %>

    <p class="notice"><%= notice %></p>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<div class="citation">
  <h1 class="mb-5">En France, une femme meurt tous les 2 jours sous les coups de son conjoint.
  </h1>
  <p>Chaque année en France, une femme sur dix entre 20 et 59 ans est victime de la violence de son partenaire, soit environ 220 000 femmes. En 2018, 121 en sont mortes ; 149 en 2019. En somme, En 2019 une femme meurt tous les 2 jours en France, sous les coups de son conjoint.
  Une violence qui n’est pas l’apanage d’un milieu, d’une classe sociale, d’un certain type de personnalité… Mais plutôt une violence ordinaire qui touche des femmes et des hommes ordinaires.
  La prise en charge des victimes de violences a souvent lieu après les faits. <strong>Ensemble, changeons cela ! Nous vous croyons, nous vous aidons.</strong>
  </p>

  <h1 class="mt-5">💪 AGISSONS ENSEMBLE</h1>
</div>

<div class="section section-demandeur">
  <div class="d-flex flex-column align-items-center">
    <p><strong>En première ligne des personnes victimes de violences</strong></p>
      <span></span>
    <p>Que vous soyez écoutant.es 3919, 15, 17, médecin, pharmacien.ne... vous pouvez aider et sauver cette personne en danger en contactant les hébergements sécurisées disponibles actuellement.</p>

    <a class="btn btn-demandeur mt-4" href="/hebs">Trouver un hébergement</a>
  </div>
    <img src="<%= image_path('map.svg') %>"/>

</div>

<div class="section section-hebergeur">
  <img src="<%= image_path('homebuild.svg') %>"/>

  <div class="d-flex flex-column align-items-center">
    <p><strong>Vous avez un hébergement vide, meublé et sécurisé ?</strong></p>
      <span></span>
    <p>Vous êtes une association habilitée, un bailleur social, un acteur public avec un ou plusieurs logements meublés, un presbytère... pouvant accueillir un.e victime de violences conjugales rapidement et sur une durée indéterminée, réferencez-le sur la plateforme !</p>

    <a class="btn btn-foyer mt-4" href="/hebs/new">Proposer un hébergement</a>
  </div>

</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: url(<%= asset_path 'women.svg' %>);">
<div class="container">

      <div class="texts-banner">

        <h1>Ensemble, trouvons des solutions d'hébergement sécurisées et réconfortantes, rapidement et systématiquement</h1>

  <!--       <p class="mt-5">Parce-qu'aucune femme ne devrait vivre dans la peur et la violence.</p> -->
        <div class="boutons mt-4 mb-4 d-flex flex-row">
          <a class="btn btn-demandeur" href="/hebs">Trouver un hébergement</a>
          <a class="btn btn-foyer" href="/hebs/new">Proposer un hébergement</a>
        </div>
      </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

<img class="logo" src="<%= image_path('PROTEGE-TOIT.png') %>"/>


<div class="list-liens">
  <h5>L'origine du projet</h5>
  <%= link_to "Investigation beta.gouv", "https://beta.gouv.fr/startups/protege-toit.html", class: "nav-link" %>
  <%= link_to "Startups d'Etat", "https://beta.gouv.fr/apropos/", class: "nav-link" %>
  <%#= link_to "Accueil", root_path, class: "nav-link" %>
</div>

<div class="list-liens">
  <h5>Contribuer au projet</h5>
  <%= link_to "Code open source sur Github", "https://github.com/JenniferStephan/protege-toit-2", class: "nav-link" %>
  <%= link_to "Ajouter des suggestions", "https://github.com/JenniferStephan/protege-toit-2/issues", class: "nav-link" %>
  <%= link_to "Nous contacter", "mailto:jennifer.stephan@beta.gouv.fr", class: "nav-link" %>
</div>

<div class="list-liens">
  <h5></h5>
  <%#= link_to "Accueil", root_path, class: "nav-link" %>
  <%#= link_to "Accueil", root_path, class: "nav-link" %>
  <%#= link_to "Accueil", root_path, class: "nav-link" %>
</div>

</div>

app/views/shared/_mini-banner.html.erb
<div class="mini-banner" style="background-image: url(<%= asset_path 'searchplace.svg' %>);">

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <img class="logo" src="<%= image_path('PROTEGE-TOIT.png') %>"/>
  <% end %>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%#= link_to "Accueil", root_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Liste des hébergements", hebs_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Proposer un hébergement", new_heb_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Kit partenaire", "https://jenniferstephanme.gitbook.io/protege-toit/", class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Se connecter", new_user_registration_path, class: "nav-link" %>
      </li>

    </ul>
  </div>
</div>